GET http://localhost:3333/api/alunos

###
GET http://localhost:3333/api/alunos/22

###
POST http://localhost:3333/api/alunos
Content-Type: application/json

{
  "nome": "Enzo",
  "sobrenome": "Cassão",
  "data_nascimento": "2009-06-10T12:00:00.000Z",
  "endereco": "Rua do Bababapow, 911",
  "email": "enzocassao@gmail.com",
  "celular": "16991916745"
}

###
PUT http://localhost:3333/api/alunos/22
Content-Type: application/json

{
  "nome": "Enzo",
  "sobrenome": "Marini",
  "data_nascimento": "2009-06-10T12:00:00.000Z",
  "endereco": "Rua do Bababapow, 911",
  "email": "enzocassao@gmail.com",
  "celular": "16991916745"
}

###
DELETE http://localhost:3333/api/alunos/22